### ISSUE TITLE
Run without writing the file to disk

### ISSUE THREAD

**Issue by caillou** [rsms/estrella#18]
I am using estrella to generate `scss` files in my build process.

As a consequence, the outfile is not needed.

Using `esbuild`, I can do the following: `esbuild --platform=node --target=node14.15.0 index.ts | node`.

Would it be possible to use `estrella`'s `-run` and `-watch` functions without writing the file to disk?

**Comment by rsms** [comment]
[v1.3.0](https://github.com/rsms/estrella/releases/tag/v1.3.0) which was just published enables this. Simply omit the `outfile` (and `outdir`) properties to build, and no file will be written. Instead the output is delivered as text to the `onEnd` function:

```js
build({
  entry: "main.js",
  sourcemap: true,
  onEnd(config, result) {
    // do something with the generated code
    console.log("output js:", result.js)
    console.log("output source map:", JSON.parse(result.map))
  },
})
```

If you just want to run the built product, don't specify `outfile` and run your build script (or estrella directly) with `-run`.
