### ISSUE TITLE
Support any version of esbuild

### ISSUE THREAD

**Issue by GeoffreyBooth** [rsms/estrella#19]
I would like to use Estrella, but I am concerned that it doesn’t support the latest `esbuild`:

https://github.com/rsms/estrella/blob/94b75b5989f136648c8552956274f680aa3e8bb9/package.json#L44-L45

Would you consider moving the `esbuild` dependency into [`peerDependencies`](https://nodejs.org/en/blog/npm/peer-dependencies/)? Ideally as `"esbuild": "*"` so that users are free to install any version of `esbuild`, and in the README you can note which versions you’ve tested Estrella against.

**Comment by kossnocorp** [comment]
Just in case if others need this, I published a temporal fork that moves `esbuild` to `peerDependecies`: `@kossnocorp/estrella@1.2.10`. You can see the changes I've made: https://github.com/kossnocorp/estrella/commit/005150b59e539658c485a2631b1935c9d7388457

**Comment by rsms** [comment]
I've considered marking esbuild as peer dependency but that would mean that installing estrella alone does not give you a functional program; you'd have to ask users to also install esbuild. A better option might be to require a less specific version, which means a project using estrella can be more exact about what esbuild version it wants.

Also, the esbuild API has changed in the past and will likely change again, at least before a 1.0 release, so it would be risky to depend on _any_ esbuild version.

**Comment by rsms** [comment]
> Just in case if others need this, I published a temporal fork that moves `esbuild` to `peerDependecies`: `@kossnocorp/estrella@1.2.10`. You can see the changes I've made: [kossnocorp@005150b](https://github.com/kossnocorp/estrella/commit/005150b59e539658c485a2631b1935c9d7388457)

This is likely going to cause you headache down the road when esbuild's API changes in a way incompatible with some version of estrella. Better would be to define a range (e.g. `>=0.6.0 <1.0.0`) or a prefix (e.g. `0.*`)

**Comment by jimrandomh** [comment]
I put an esbuild version in the `resolutions` section of my package.json (which is a `yarn`-specific feature I think). It seems to work, except for a warning message on startup that some recently-introduced esbuild flags might be invalid.

**Comment by rsms** [comment]
Published in [v1.3.0](https://github.com/rsms/estrella/releases/tag/v1.3.0)
