### ISSUE TITLE
Exiting process after building, even with -watch enabled

### ISSUE THREAD

**Issue by jonathontoon** [rsms/estrella#2]
As the title suggests I am using Estrella directly in the command-line, invoked through a package.json script. When doing so and applying the -watch flag it seems to exit the process directly after, without persisting (which I guess is what I expected). Just curious if -watch only compatible through invoking Estrella via a build script?

This is with using Node v12.16.3. Cheers!

**package.json**
```
  "scripts": {
    "watch": "estrella -watch -minify -bundle ./src/index.js -o ./public/bundle.js"
  }
```

**script invoke**
```
yarn watch
```

**console output**
```
Wrote ./public/bundle.js (1.5kb, 3.89ms)
Watching files for changes...
Done in 0.13s.
```

**Comment by rsms** [comment]
Good find. Thanks Jonathon!
In addition to fixing this bug I also introduced tests for verifying this doesn't break in the future (`./test/test.sh test/watchdir` to run those tests)

Try upgrading estrella to >=1.0.8 (`yarn upgrade estrella`)
