### ISSUE TITLE
Use incremental build feature of esbuild

### ISSUE THREAD

**Issue by schickling** [rsms/estrella#20]
Thanks again for this great tool @rsms 🙏 

To speed up estrella further when continuously rebuilding a project, it's [now possible](https://github.com/evanw/esbuild/issues/21#issuecomment-731613431) to use the new [incremental build feature](https://esbuild.github.io/api/#incremental).

Note: I've done some quick scan of the code base if this is already the case but couldn't find any indication for this. If you're already using esbuild's incremental build feature, please just close this issue.

**Comment by rsms** [comment]
Great idea! Happy to accept a PR for this, by the way.

**Comment by myobie** [comment]
`{ incremental: !!cliopts.watch }` appears to me to be passed through to `esbuild`. Is there more to do than just include it in the build arguments?

**Comment by rsms** [comment]
Added in 7a2bd8f2d6b7c36ff888d853ac9b0e345bfddd65 (forgot to mention the GitHub issue) and will be included with the next release.
