### ISSUE TITLE
Child not killed if it's a shell command

### ISSUE THREAD

**Issue by jimrandomh** [rsms/estrella#21]
When I run `build.js -watch` with a build script like this:
```
build({
  outfile: './build/server/js/serverBundle.js',
  run: "node -r source-map-support/register -- ./build/server/js/serverBundle.js --settings settings.json",
  //...
})
```
this results in a shell process (`sh -c node -r `...) which spawns a node process. Killing the watcher with ^C/SIGINT kills the shell process, but leaves the node process still running in the background. Changing this to
```
  run: ["node", "-r", "source-map-support/register", "--", "./build/server/js/serverBundle.js", "--settings settings.json"],
```
seems to work around the issue (it spawns node without the shell wrapper).

**Comment by rsms** [comment]
This is a "feature" of bash (and Bourne-compatible shells like zsh); to not kill its child processes on exit. When you pass a string to Estrella's "run" option, it asks NodeJS to run the process in a shell which is most likely going to be bash (or zsh if you are on macOS) and thus, your experience with zombie processes.

You can try the following to have bash kills all its child processes when it exits: (in your bash script)

```sh
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT
```

Your `run: ["node", "-r ...` solution is even better as it avoids starting a shell — you should just do that :–)
