### ISSUE TITLE
Windows clone issues with src/aux.ts

### ISSUE THREAD

**Issue by vancura** [rsms/estrella#25]
Hi Rasmus,

It seems it's currently impossible to clone on Windows. I tried SSH and HTTPS, no luck.

```
D:\Repos\Libraries>git clone git@github.com:rsms/estrella.git
Cloning into 'estrella'...
Enter passphrase for key '/c/Users/vacla/.ssh/id_rsa':
remote: Enumerating objects: 280, done.
remote: Counting objects: 100% (280/280), done.
remote: Compressing objects: 100% (176/176), done.
remote: Total 1003 (delta 158), reused 199 (delta 97), pack-reused 723
Receiving objects: 100% (1003/1003), 1.43 MiB | 793.00 KiB/s, done.
Resolving deltas: 100% (579/579), done.
error: invalid path 'src/aux.ts'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Is there anything specific about this file that stops the repo from cloning on Windows?

Enjoy the break! :)

Vaclav

**Comment by vancura** [comment]
I also tried a fresh Windows 10 installation with clean Git 2.92.2 – no .gitconfig was on the machine before, to prevent any wrong settings that could cause the issue. The same thing, I have no idea where that could be. I thought it could be in the forward slash, but Git should be able to handle that.

**Comment by benmerckx** [comment]
See: https://stackoverflow.com/questions/61614004/cloning-succeded-but-checkout-failed-due-to-invalid-path-what-is-the-path-probl/61616948#61616948

Basically windows (and any software running on it) refuses to work with any file named aux, regardless the extension. To make changes you can rename it in a unix environment or use githubs interface.

**Comment by vancura** [comment]
Thanks a lot, @benmerckx! Frankly, that's ridiculous what Windows does there :)

**Comment by rsms** [comment]
What an incredible bug. Thank you @vancura for all the help. You should be able to put the source code on Windows now, after 25f04867f6f13a1a9d990df4a7a2f7ecb632071c

**Comment by vancura** [comment]
Perfect, thanks a lot, @rsms! :)

**Comment by vancura** [comment]
Also, credit where it's due: @benmerckx found the origins of this peculiarity, not me :)
