### ISSUE TITLE
Broken sourcemaps

### ISSUE THREAD

**Issue by jimrandomh** [rsms/estrella#28]
After each build, `patchSourceMap` modifies the source-maps esbuild emitted, deleting the `sourcesContent` field and setting `sourceRoot` to a relative path from the output directory to the working directory. In practice, if the output file is a webap, this breaks source mapping; the relative path doesn't point anywhere sensible when it's treated as a UR. Commenting out the call to `patchSourceMap` fixes it, as does using `sourcemap:"inline"` (but the latter drastically increases the size of the output javascript bundle).

**Comment by rsms** [comment]
Shipped with [release 1.4.0](https://github.com/rsms/estrella/releases/tag/v1.4.0)
