### ISSUE TITLE
Warn about naming my own build script `estrella.js`

### ISSUE THREAD

**Issue by maxkrieger** [rsms/estrella#31]
After about an hour of confusion I realized I should *not* be calling my `build.js` as `estrella.js`, since the package's own `estrella.js` will mistake it for running itself (https://github.com/rsms/estrella/blob/25f04867f6f13a1a9d990df4a7a2f7ecb632071c/src/estrella.js#L1022). This results in an unrelated `missing <srcfile> argument (see ${prog} -help)` error.

I think the README should at least warn about this, if the heuristic can't be changed. I imagine I'm not the only one calling the file `estrella.js` since there's the convention `rollup.config.js` and `webpack.config.js`.

**Comment by rsms** [comment]
Oh good catch!

**Comment by rsms** [comment]
Will be included in the next release (1.3.4)

**Comment by rsms** [comment]
Shipped with [release 1.4.0](https://github.com/rsms/estrella/releases/tag/v1.4.0)
