### ISSUE TITLE
Watch mode breaks for esbuild v0.9.0

### ISSUE THREAD

**Issue by danielberndt** [rsms/estrella#32]
After upgrading to esbuild 0.9.0 I'm receiving this error message

> error: "metafile" must be a boolean

Looking at the [release notes](https://github.com/evanw/esbuild/releases/tag/v0.9.0) it seems that the metafile attribute now only needs to be `true` rather than pointing to a file.

If I put `{metafile: true}` into my estrella build config I'm receiving this though:

> The "path" argument must be of type string or an instance of Buffer or URL. Received type boolean (true)

**Comment by geoffreylitt** [comment]
If anyone wants an immediate band-aid workaround, I made [a fork](https://github.com/geoffreylitt/estrella) that simply restricts estrella to use esbuild < 0.9.0. You can install like this:

```
"devDependencies": {
  // ...
  "estrella": "https://github.com/geoffreylitt/estrella",
  // ...
}
```

Obviously doesn't solve the underlying issue, and I'm sure there are better ways to do this, but this worked for me when I needed to build a project this morning

**Comment by rsms** [comment]
Oh yikes. Estrella uses the metafile contents to know what files were included in the compilation. It uses this information to know what files to watch for changes. I'm looking into this now.

**Comment by rsms** [comment]
Aside: esbuild now has the ability to watch its source files and rebuild. However estrella can probably not rely on that since it wouldn't include other files (like for example CSS), at least that's my understanding. The esbuild JS API provides the ability to get a call-back when it has rebuilt js code (`WatchMode.onRebuild`)

**Comment by rsms** [comment]
Hm, it seems there's no way to get to the `Metafile` information in esbuild 0.9 after the initial build. Quick example:

```js
const results = await esbuild.build({
  minify: true,
  sourcemap: false,
  logLevel: 'info',
  outfile: 'out/main.js',
  entryPoints: [ 'main.ts' ],
  metafile: true,
  watch: {
    onRebuild(error, result) {
      console.log("onRebuild", {error, result})
    }
  },
})
console.log(results)
```

Output:

```
{ warnings: [], errors: [] }
[watch] build finished, watching for changes...
```

Note that `onRebuild` is not called on initial build and that the `BuildResult` does not contain a `metafile` object.
Now if I make a change to the `main.ts` source file:

```
[watch] build started (change: "main.ts")
[watch] build finished
onRebuild { error: null, result: { warnings: [], stop: [Function: stop] } }
```

Note that `metafile` is missing from `onRebuild`'s `result` object.

If I just run esbuild without watch, but with `metafile:true` the resulting value from `build()` is the same; also lacking `metafile`:

```js
const results = await esbuild.build({
  minify: true,
  sourcemap: false,
  logLevel: 'info',
  outfile: 'out/main.js',
  entryPoints: [ 'main.ts' ],
  metafile: true,
})
console.log(results) // => { warnings: [], errors: [] }
```

From esbuild's typescript definitions: (excerpt for brevity)

```ts
declare function build(options: BuildOptions): Promise<BuildResult>;
interface BuildOptions extends CommonOptions {
  metafile?: boolean;
  watch?: boolean | WatchMode;
}
interface WatchMode {
  onRebuild?: (error: BuildFailure | null, result: BuildResult | null) => void;
}
interface BuildResult {
  warnings: Message[];
  outputFiles?: OutputFile[]; // Only when "write: false"
  rebuild?: BuildInvalidate; // Only when "incremental: true"
  stop?: () => void; // Only when "watch: true"
  metafile?: Metafile; // Only when "metafile: true"
}
```

[Esbuild's documentation on metafile](https://esbuild.github.io/api/#metafile) seems to not be up to date or to be specific to the CLI (not the JS API.)

This may be a bug in esbuild or I'm misunderstanding its API.

**Comment by rsms** [comment]
c318a5653dc1550952aa520c13793c0aec3fe52c adds support for esbuild 0.9 which is included in just-[released NPM package estrella 1.3.1](https://www.npmjs.com/package/estrella/v/1.3.1)

@danielberndt and @geoffreylitt, would you mind testing this out and letting me know if it resolves this issue? Thanks!

**Comment by geoffreylitt** [comment]
@rsms thanks for fixing this so quickly! Just upgraded to 1.3.1 and it's working great :)

**Comment by rsms** [comment]
Thank you both for your contributions!

**Comment by danielberndt** [comment]
Thank _you_ @rsms for the quick fix! ❤️

Just upgraded to the esbuild 0.9.0 and estralla 1.3.3 and it all works like a charm :)
