### ISSUE TITLE
Bumb to latest esbuild version.

### ISSUE THREAD

**Issue by arkadiy93** [rsms/estrella#36]
Hello,

Esbuild have been updated to a new version, and they have added a nice feature. 

[esbuild pr](https://github.com/evanw/esbuild/pull/1078)

All tests seem to pass with the new esbuild version.
Can I create a PR or maybe you can make an update?

**Comment by rsms** [comment]
Shipped in [v1.4.1](https://github.com/rsms/estrella/releases/tag/v1.4.1)
