### ISSUE TITLE
Watching subdirectories unavailable on Linux

### ISSUE THREAD

**Issue by jonathontoon** [rsms/estrella#4]
Hey @rsms I wasn't immediately sure if this was something on estrella's end or a limitation of esbuild, so excuse my assumptions if they're off!

When I have an entry point file which is importing a module from a sub-directory, estrella only seems to execute a rebuild when something changes in the entry-point file. However if I move my files from the sub-directory to the same directory as the entry-point file, things will rebuild when any file is changed.

I guess my expectation would be to have files, which are referenced by the entry-point file but are not in the base-level directory, trigger a rebuild when they change.

An example set up running on Node 12.16.3.

**./src/index.js**
```
import MyModule from "./modules/my-module";

(function () {
  
   MyModule.foo();
   // returns string bar

})();
```

**./src/modules/my-module.js**
```
const MyModule = (function () {

   return {
       foo: function () {
           return "bar";
       }
   };

})();

export default MyModule;
```

**./build.js**
```
#!/usr/bin/env node

const path = require("path");
const { build, cliopts } = require("estrella");
const { createServer } = require("serve-http");

const options = {
  entry: "./src/index.js",
  outfile: "./public/bundle.js",
  bundle: true,
  minify: true
};

build(options);

cliopts.watch && createServer({
  port: 3000,
  pubdir: path.join(__dirname, "./public"),
});
```

Thus far whenever I change anything within `my-module.js` a rebuild won't trigger. Only when the change is within `index.js`.

**Comment by rsms** [comment]
What OS are you running this on?

**Comment by jonathontoon** [comment]
Currently on Ubuntu 18.04.4 LTS via WSL. Your favorite, I know. ;)

**Comment by rsms** [comment]
I actually have a dedicated Ubuntu MacBook in my office :–)

Unfortunately this is a limitation with NodeJS's `fs.watch` function. [The documentation mentions](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_caveats) "The recursive option is only supported on macOS and Windows."

I'll rename this issue to be about improving deep-directory watch support. There are a lot of 3rd party libraries implementing this in JS but they are all rather heavy and I'm trying to keep estrella small.

In the meantime, what you can do is some hack like this:

```js
#!/usr/bin/env node
const { build, scandir, watchdir } = require("estrella")
const fs = require("fs")
build({
  entry: "src/main.ts",
  outfile: "out/foo.js",
})
const srcSubdirs = [ "src/meow", "src/woff" ] // fs.readdir to automate
cliopts.watch && watchdir(srcSubdirs, /\..*$/i,() => {
  fs.writeFileSync("src/dummy.js", "")  // this would trigger a rebuild
})
```

**Comment by rsms** [comment]
Idea: Somehow ask esbuild for sources. It resolves all imports and thus after the initial build should know about all _in use_ subdirectories. It might be even better than just blindly rebuilding whenever a file changes.

**Comment by jonathontoon** [comment]
Thanks for the tip, that should probably suffice in the short term. I agree with the philosophy of keeping things nice and nimble so take your time.

**Comment by rsms** [comment]
I added chokidar in a branch (https://github.com/rsms/estrella/tree/fswatch). Unfortunately chokidar relies on a another third-party library which uses a "native" nodejs module which esbuild is unable to bundle (naturally, since it needs to be built for every platform.) This means that the average execution time goes from ~35ms to ~60ms on my machine. I suspect a majority of this increase is from nodejs loading the native code module (a `.node` "module") and wiring it up.

There are other upsides beyond Linux support with chokidar. For example, some code in estrella can be removed as chokidar implements it. This would reduce the effort to maintain estrella, which is good.

@jonathontoon if you're interested, you could check out the "fswatch" branch (`git fetch --all && git checkout fswatch && ./build.js` and use the file "dist/estrella.js")

**Comment by jonathontoon** [comment]
Thanks @rsms will try it out and report back.

Alternatively I also hacked something together using `node-watch` which has a significantly smaller footprint than `chokidar` (less battle tested though). I don't get the warm and fuzzy feeling of seeing estrella's nice console logs but it solves the problem on Linux for the short term. 😄 

```
#!/usr/bin/env node

(function () {

  const watch = require("node-watch");
  const path = require("path");

  const { build } = require("esbuild");
  const { createServer } = require("serve-http");

  const buildOptions = {
    entryPoints: ["./src/index.js"],
    outfile: "./public/bundle.min.js",
    bundle: true,
    minify: true,
    target: "es2015"
  };

  if (process.env.NODE_ENV === "production") {
    build(buildOptions);
  } else {
    watch("./src", { recursive: true }, function () {
      build(buildOptions);
    });

    createServer({
      port: 3000,
      pubdir: path.join(__dirname, "./public"),
    });
  }

})();
```

**Comment by rsms** [comment]
Oh, I hadn't heard of [node-watch](https://github.com/yuanchuan/node-watch) — it looks pretty good.

**Comment by rsms** [comment]
Closing since Estrella now uses chokidar and thus supports Linux
