### ISSUE TITLE
How to turn off TypeScript diagnostics?

### ISSUE THREAD

**Issue by AlCalzone** [rsms/estrella#40]
I have a project where I need to turn off TypeScript diagnostics for one build. I don't seem to be able to do it, no matter what I set for the `tslint` and/or `tsc` options. Any hints what I might try?

**Comment by rsms** [comment]
```js
build({
  // ...
  tslint: false,
  // ...
})
```

Here in the documentation :-)
https://github.com/rsms/estrella/blob/33ede3c7bad132dfbe6901eb34bccb50694b9584/estrella.d.ts#L54-L66

**Comment by AlCalzone** [comment]
Well... I feel stupid now.

I could swear I had `tslint: false` in the config. Tried again and now it works.

**Comment by rsms** [comment]
Ha, ha... Sometimes its hard to see the forest for the trees :–)
