### ISSUE TITLE
nodemon like option

### ISSUE THREAD

**Issue by holtwick** [rsms/estrella#7]
I love estrella, hope you will continue to work on it.

Some users probably have a scenario where they would like to start a the resulting code using `node` any time the source changes. Usually this is done using `nodemon`. I wrote a little workaround, not being sure if this is a smart way to do it:

```js
#!/usr/bin/env node

const pkg = require('./package.json')
const common = require('./build.config.js')
const { spawn } = require('child_process')
const { build } = require('estrella')

let node

build({
  ...common,
  entry: 'src/index.js',
  outfile: pkg.main,
  onEnd(config, result) {
    if (config.watch) {
      if (node) {
        node.kill('SIGHUP')
        node = null
      }
      if (result.errors.length > 0) {
        console.error(`Build failed with ${result.errors.length} errors`)
      } else {
        console.info(`Build succeeded. Launching 'node ${pkg.main}'`)
        node = spawn('node', [pkg.main], {
          shell: true,
          stdio: 'inherit',
        })
      }
    }
  },
})
```

In case it is, it would be great to get an estrella option to say, start the `outFile` with node, like:

```js
#!/usr/bin/env node

const pkg = require('./package.json')
const common = require('./build.config.js')
const { buildAndRun } = require('estrella')

buildAndRun({
  ...common,
  entry: 'src/index.js',
  outfile: pkg.main
})
```

Thanks!

**Comment by holtwick** [comment]
It would certainly be better to make it a command line option, like:

```sh
./build.js -watch -run
```

This way it could also would also work  without `-watch`, which looks like a more consistence user experience.

**Comment by rsms** [comment]
Oh, nice idea.
I usually use [`autorun`](https://github.com/rsms/rsms-utils#autorun) in a second shell when programming reactively.

With the `-run` CLI argument, what would you do if the build script builds multiple programs? Would you run them all or run the first one defined?

I think "run them all" is the answer. Optionally only products that are executables could be selected for being run (i.e. when the executable bit is set in the outfile's mode, which can be controlled via the `outfileMode:"+x"` build property.)

For example:

```js
const { build } = require('estrella')
build({
  entry: "src/tool.js",
  outfile: "dist/bin/tool",
  outfileMode:"+x",
})
build({
  entry: "src/lib.js",
  outfile: "dist/lib.js",
})
```

Running `./build.js -run` would run `dist/bin/tool` (since it's executable) but not `dist/lib.js`

What do you think @holtwick?

**Comment by holtwick** [comment]
Happy you like the idea, @rsms. That's an interesting point. 

Running all generated files as a general rule sounds good. The developer could split up the build script in separate pieces in case there are also "only build" items.

But here some other ideas:

### runnable

A flag called `runnable` could indicate items that respond to `-run`. It could be set to `true` to indicate it is active. If set to something like `node` or `deno` it could also imply to add the `+x` chmod and add a corresponding shebang like `#!/usr/bin/env node` at top of the generated file.

```
build({
  entry:   "src/tool.js",
  outfile: "dist/bin/tool",
  runnable true,
})
```

### -run index.js

The user could also explicitly specify what should be run via passing the `outfile` as an argument. Those entries that match are then run. Multiple could be separated by `,` or multiple repetitions of `-run`. Default without further arguments would fallback to "run all" as described before. Example:

```
./build.js -run dist/server.js -run dist/tool.js
```

Anyway, I guess most of the time only one item needs to be run but the other ones being regenerated on change. I usually have server side code that needs to run and restart and then frontend code, that needs to reload in the browser.

I saw you have a reload server as well. Just in case, here is a simple solution I came up with using socket.io: https://github.com/holtwick/hostic/blob/master/src/cli-serve.js#L96

Thanks for considering to add the `-run` option.

**Comment by rsms** [comment]
Ah, I like it. Perhaps `executable:bool|string` is a better name though.
---
Funnily, I thought I had added another comment after previous one, but I had forgot to submit it :–P
<img width="941" alt="Screen Shot 2020-09-21 at 13 25 13" src="https://user-images.githubusercontent.com/47046/93817661-1f1da680-fc0e-11ea-9ddc-406be86979c5.png">
---
Another idea, if the "executable condition" approach is not right:

```js
const { build } = require('estrella')
build({
  entry:   "src/tool.js",
  outfile: "dist/bin/tool",
  run: "node $outfile -test",
})
build({
  entry:   "src/lib.js",
  outfile: "dist/lib.js",
})
```

When running `./build.js` then all products with a truthy `run` property would be selected to execute. If the value of the `run` property is a string, that string is passed to a shell to be executed, substituting `$outfile` for the path of `outfile`. (The `run` property could also support an array value of arguments to be executed instead of a shell script.)

Note the lack of `-run` CLI arg; instead the build script author can conditionally enable running certain programs.

```js
const { build } = require('estrella')
build({
  entry:   "src/tool.js",
  outfile: "dist/bin/tool",
  run: "node $outfile -test",
})
```

**Comment by holtwick** [comment]
I like the second part of your last post better. The option name `run` aligns nicely with the command line option `-run`. I also like, that this way it is possible to add additional arguments. The shebang I implemented in my PR is probably not required and could already be part of the source file, if esbuild respects it during translation.

**Comment by rsms** [comment]
Landed in v1.2.0 which was just released.

API:
https://github.com/rsms/estrella/blob/v1.2.0/estrella.d.ts#L93-L130

Example:
https://github.com/rsms/estrella/tree/v1.2.0/examples/run

@holtwick let me know what you think and how it's working for you. Thanks for the collaboration!

**Comment by holtwick** [comment]
Thanks @rsms for adding the feature. In general, it works great. 

Some little things might be nice: to have as well:

- Add the `run` option's documentation to the `README.md` file
- In my PR I added a `-r` or `-run` option. It seems to be missing here. It is important, because if somebody wants to build for production, the code is still run. Alternatively the code should only be executed if `-w` is active. A workaround would be to handle this in the `build.js` script itself, but that's not very attractive IMO.

**Comment by rsms** [comment]
v1.2.2
https://github.com/rsms/estrella/tree/v1.2.2#running-your-program

Some tests here:
https://github.com/rsms/estrella/blob/v1.2.2/test/cli-direct/test.sh

:-)

**Comment by rsms** [comment]
I considered allowing passing a value to `-run` but after some consideration I think the traps outweigh the flexibility. It would only be possible within reasonable CLI syntax to pass a string which means it would be run as shell command and not a "regular" command, which in turn means people less familiar with shells may battle with the syntax while feeling teased to use the "run" value.

For complex run setups that should only be active with the `-run` flag, I image you'll do this:

```js
const { build, cliopts } = require("estrella")
const command = ["/usr/bin/zsh", "-e", "-c", "special thing"]
const p = build({
  entry: "main.ts",
  outfile: "out/main.js",
  run: cliopts.run && command,
})
```

**Comment by holtwick** [comment]
Sorry, I'm now somewhat confused. Previously I understood that running was triggered by setting a build option: https://github.com/rsms/estrella/blob/v1.2.0/examples/run/build.js#L14

Now it looks like `-run` on the command line just runs it all and `run` option isn't required anymore. Also, the documentation describes this behavior. 

It is of course your decision, of how to implement it. I still think that the approach we discussed before makes sense. That was, having a build option identifying runnable parts. Run those ifs `-run` is passed at command line.

To break it down: the basic question is, do you want to have multiple build scripts in one file where some of them cannot be run? If the answer is yes, then I think we need a build option as well. If the answer is no, then it is fine as it is implemented right now.

BTW: The `-r` command line option does not work if used like this together with watch `-wr`
